version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=keqing
      - POSTGRES_PASSWORD=keqing
      - POSTGRES_DB=copilot-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
